liftup_test/urls.py
from django.conf.urls import url
from liftup_test.views import *

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^add/$', AddView.as_view(), name='add'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('liftup_test.urls', namespace='lift')),
]

liftup_test/models.py
from django.db import models
from django.utils import timezone


class HostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('-created')


class Host(models.Model):
    host = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(default=timezone.now)

    objects = HostManager()

liftup_test/views.py
from django.views.generic import ListView, View
from liftup_test.models import Host
from django.http import JsonResponse, HttpResponse
from django.db.utils import IntegrityError
import re

url_regexp_string = '(?:(?:https?:\/{2})?(?:((?:[0-9a-z_-]+\.)+(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cx|cy|cz|cz|de|dj|dk|dm|do|dz|ec|ee|eg|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mn|mn|mo|mp|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|nom|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ra|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sj|sk|sl|sm|sn|so|sr|st|su|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw|arpa))(?::[0-9]+)?(?:(?:\/(?:[~0-9a-zA-Z\#\+\%@\.\/_-]+))?(\?[0-9a-zA-Z\+\%@\/&\[\];=_-]+)?)?))'
url_regexp = re.compile(url_regexp_string, re.IGNORECASE)


class IndexView(ListView):
    template_name = 'liftup_test/index.html'
    model = Host

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['regexp'] = url_regexp_string.replace('\\', '\\\\')
        return context


class AddView(View):
    def post(self, request):
        if 'url' not in request.POST:
            return HttpResponse(status=400)

        # Do NOT trust a client and check the url on the server side
        url = request.POST['url']
        matches = url_regexp.match(url)

        if not matches:
            # Bad URL
            return HttpResponse(status=400)

        url = matches.group(1).lower()
        try:
            host = Host(host=url)
            host.save()
        except IntegrityError:
            # Duplicate entry
            return HttpResponse(status=400)

        return JsonResponse({
            'url': host.host,
            'created': host.created.utcnow().timestamp(),
        })

templates/layout.html
<!doctype html>
{% load static %}
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}Test{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static "css/normalize.min.css" %}">
        <link rel="stylesheet" href="{% static "css/font.css" %}">
        <link rel="stylesheet" href="{% static "css/main.css" %}">

        <script src="{% static "js/vendor/modernizr-2.8.3.min.js" %}"></script>
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        {% block extrabody %}{% endblock %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="{% static "js/main.js" %}"></script>
    </body>
</html>

templates/liftup_test/index.html
{% extends 'layout.html' %}
{% load %}

{% block content %}
    <form action="{% url 'lift:add' %}" method="post" id="url-form">
        <label for="url-input">Website URL:</label>
        <input id="url-input" name="url" placeholder="example.com" type="text">
        <div id="help-text">Wrong URL</div>
    </form>
    <ul id="url-list">
        {% for object in object_list %}
            <li id="url-item-{{ object.host }}">{{ object.host }}</li>
        {% endfor %}
    </ul>
{% endblock %}

{% block extrabody %}
    <script>
        var config = {
            regex: '{{ regexp | safe }}',
            host_add_url: '{% url 'lift:add' %}',
            objects: [
                {% for object in object_list %}
                    {
                        url: '{{ object.host }}',
                        created: {{ object.created.utcnow.timestamp }}
                    },
                {% endfor %}
            ]
        };
    </script>
{% endblock %}